// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crypto-finance/src/cmd"
	"crypto-finance/src/domain/usecase"
	"crypto-finance/src/presentation/controller"
)

// Injectors from wire.go:

func initializeApp() (*App, error) {
	firebaseRepository := cmd.NewFirebaseRepository()
	authUseCase := usecase.NewAuthUseCase(firebaseRepository)
	authController := controller.NewAuthController(authUseCase)
	statusController := controller.NewStatusController()
	httpRepository := cmd.NewHttpRepository()
	appServer := cmd.NewAppServer(authController, statusController, httpRepository)
	app := &App{
		Server: appServer,
	}
	return app, nil
}

// wire.go:

type App struct {
	Server cmd.ServerStarter
}
